name: Backend CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      # Se estes secrets não existirem, o passo do Sonar é ignorado (condicional)
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Test (JaCoCo)
        run: mvn -B test

      - name: SonarCloud Scan (optional)
        if: ${{ env.SONAR_TOKEN != '' && env.SONAR_PROJECT_KEY != '' && env.SONAR_ORG != '' }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: backend
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

      - name: Package
        run: mvn -B -DskipTests package

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco